extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();
    let output_file = PathBuf::from(&crate_dir)
        .join("header")
        .join(format!("{}.h", package_name));

    // Configure cbindgen
    let mut config = cbindgen::Config::default();
    config.language = cbindgen::Language::C;
    config.style = cbindgen::Style::Both;
    config.header = Some(format!(
        "/* Generated by cbindgen for {} {} */",
        package_name,
        env::var("CARGO_PKG_VERSION").unwrap()
    ));
    config.include_guard = Some(format!("{}_H", package_name.to_uppercase()));
    config.autogen_warning = Some(
        "/* Warning: This file is automatically generated by cbindgen. \
                           Do not modify this file directly. */"
            .to_string(),
    );

    // Generate the C header
    match cbindgen::generate_with_config(&crate_dir, config.clone()) {
        Ok(bindings) => {
            bindings.write_to_file(&output_file);
        }
        Err(err) => {
            eprintln!("Error generating C bindings: {}", err);
            std::process::exit(1);
        }
    }
}
