extern crate cbindgen;

use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();

    // Define the output path for the header file
    let header_output_path = PathBuf::from(&crate_dir).join("header"); // Corrected to singular "header" as per existing setup
    if !header_output_path.exists() {
        std::fs::create_dir_all(&header_output_path).expect("Failed to create header directory");
    }
    let output_file = header_output_path
        .join(format!("{}.h", package_name))
        .display()
        .to_string();

    let mut config = cbindgen::Config::default();
    config.language = cbindgen::Language::C;
    config.style = cbindgen::Style::Both; // Kept from previous working config
    config.header = Some(format!(
        "/* Generated by cbindgen for {} {} */",
        package_name,
        env::var("CARGO_PKG_VERSION").unwrap()
    ));
    config.include_guard = Some(format!("{}_H", package_name.to_uppercase()));
    config.autogen_warning = Some(
        "/* Warning: This file is automatically generated by cbindgen. \
                           Do not modify this file directly. */"
            .to_string(),
    );
    // Add other configurations here if needed, for example:
    // config.include_guard = Some(format!("{}_h", package_name.to_uppercase()));
    // config.autogen_warning = Some("/* Generated by cbindgen, do not edit by hand */".to_string());

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_config(config)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&output_file);

    // This part is for C test "linting" or early check, can be removed if causing issues
    // or if the integration test handles all C compilation.
    // For now, I will keep the rerun-if-changed lines as they are generally useful.
    let c_test_file = PathBuf::from(&crate_dir)
        .join("tests")
        .join("c_api_tests.c");
    if c_test_file.exists() {
        println!("cargo:rerun-if-changed=tests/c_api_tests.c");
        println!("cargo:rerun-if-changed=header/vi.h");
    }
}
