/* Generated by cbindgen for vi 0.8.0 */

#ifndef VI_H
#define VI_H

/* Warning: This file is automatically generated by cbindgen. Do not modify this file directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Transforms an input string using the specified Vietnamese input method.
 *
 * # Safety
 *
 * - `method_type` must be a pointer to a valid null-terminated C string.
 * - `input_buffer` must be a pointer to a valid null-terminated C string.
 * - `output_buffer` must be a pointer to a mutable character buffer of at least `output_buffer_size` bytes.
 * - `output_buffer_size` must be large enough to hold the transformed string, including the null terminator.
 *   It is recommended to allocate a buffer of the same size as the input buffer, plus one for the null terminator,
 *   as the transformed string can sometimes be larger than the input.
 */
int transform_buffer_c(const char *method_type,
                       const char *input_buffer,
                       char *output_buffer,
                       uintptr_t output_buffer_size);

#endif /* VI_H */
